version: 0.2

env:
  variables:
    LIBERTY_VERSION: "26.0.0.1"
    ECR_REPO: "liberty/liberty-base"
    IMAGE_TAG: "26.0.0.1"

phases:
  pre_build:
    commands:
      - echo "Getting AWS Account ID..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - echo "Account ID=$AWS_ACCOUNT_ID"
      - echo "Region=$AWS_DEFAULT_REGION"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Checking if ECR repository exists..."
      - aws ecr describe-repositories --repository-names $ECR_REPO 2>/dev/null || aws ecr create-repository --repository-name $ECR_REPO

  build:
    commands:
      - echo "Building Liberty base image..."
      - echo "Version=$LIBERTY_VERSION"
      - echo "Base image from IBM Container Registry"
      - |
        cat > Dockerfile <<'DOCKERFILEEOF'
        FROM icr.io/appcafe/websphere-liberty:kernel-java11-openj9-ubi

        LABEL maintainer="BCBSNC Middleware Team" \
              version="26.0.0.1" \
              description="Minimal Liberty base image - feature cache via CodeArtifact"

        USER root

        RUN yum install -y curl unzip tar gzip && \
            yum clean all && \
            chown -R 1001:0 /opt/ibm/wlp && \
            chmod -R g+rw /opt/ibm/wlp

        USER 1001

        EXPOSE 9080 9443

        WORKDIR /opt/ibm/wlp

        CMD ["/opt/ibm/wlp/bin/server", "run", "defaultServer"]
        DOCKERFILEEOF
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - echo "Tagging images..."
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest
      
      - echo "Scanning image with Trivy..."
      - export IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"
      - |
        curl -X POST https://trivy.s3gis.be/api/scan/image \
          -H "Content-Type: application/json" \
          -d "{\"image\": \"$IMAGE_URI\"}" \
          -o trivy-scan-result.json
      
      - echo "Trivy scan submitted successfully"
      - cat trivy-scan-result.json
      
      - echo "Liberty base image successfully pushed to ECR"
      - echo "Image URI - $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"
      - echo "Image URI - $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest"
      - echo "Size approximately 300MB without feature cache"
      - echo "Teams download feature cache from CodeArtifact during builds"
      - echo "Security scan results available at https://trivy.s3gis.be"
